services:
  www-server:
    image: jhops881/www-server-image:dev
    restart: always

  reverse-proxy:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - www-server
      - api-server
    restart: always
