services:
  frontend:
    image: jhops881/frontend:dev
    restart: always

  backend:
    image: jhops881/backend:dev
    restart: always

  reverse-proxy:
    image: jhops881/reverse-proxy:dev
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    restart: always
