services:
  www-frontend:
    image: jhops881/www-frontend:dev
    restart: always

  www-backend:
    image: jhops881/www-backend:dev
    restart: always

  reverse-proxy:
    image: jhops881/reverse-proxy:dev
    ports:
      - 80:80
    depends_on:
      - www-frontend
      - www-backend
    restart: always
