services:
  www-server-a:
    build: ./www
    restart: always

  www-server-b:
    build: ./www
    restart: always

  api-server-a:
    build: ./api
    restart: always

  api-server-b:
    build: ./api
    restart: always

  reverse-proxy:
    image: nginx:stable
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - www-server-a
      - www-server-b
      - api-server-a
      - api-server-b
    restart: always
